name: Netlify Auto Deploy

on:
  push:
    branches:
      - main # Set the branch that will trigger the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.18.0" # Set the Node.js version you are using

      - name: Install dependencies
        run: yarn install # or yarn install if you use yarn

      - name: Build the project
        run: yarn run build # or yarn build if you use yarn

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1
        with:
          publish-dir: ./build # Set the output folder for your build (e.g., Next.js might use `.next` or `out`)
          production-branch: main # Specify your production branch
          deploy-token: ${{ secrets.NETLIFY_TOKEN }} # Netlify deployment token (we'll set this up in the next step)
